In [7]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [8]:
import librosa as lr
import numpy as np
import torch

In [67]:
filepath = r"C:\Users\jiyun\Desktop\Jiyu\2020-2021\ESC499 - Thesis\WaveNet\magnatagatune\data\24_preludes_for_solo_piano\jan_hanford-24_preludes_for_solo_piano-01-prelude_no__1_in_f_minor-30-59.mp3"
ytrain, sr = lr.load(filepath)

In [17]:
np.sum([2 ** i for i in range(10)])

1023

In [43]:
from model import WaveNet
from data_processing import Dataset

In [44]:
model = WaveNet()

In [79]:
filepath = r"C:\Users\jiyun\Desktop\Jiyu\2020-2021\ESC499 - Thesis\WaveNet\magnatagatune\data\24_preludes_for_solo_piano"
dataset = Dataset(filepath)

In [10]:
len(dataset)

50

In [81]:
dataset[0][1].max()

tensor(254)

In [27]:
np.random.seed

<function RandomState.seed>

In [23]:
from torch.utils import data

In [76]:
loadtr = data.DataLoader(dataset, batch_size=1,shuffle=True,num_workers=0,worker_init_fn=np.random.seed)

In [70]:
for iloader, ytrain in loadtr:
    ytrain.max()

KeyboardInterrupt: 

In [99]:
dilations1 = [2 ** i for i in range(10)] * 1
field = np.sum(dilations1) + 1

In [100]:
field

1024

In [56]:
model(ytrain[:, 1024:1024 + 16000].to('cuda'))

NotImplementedError: 

In [90]:
y.size(2)-(self.rf-2)

torch.Size([1, 1, 642185])

In [98]:
torch.zeros(1, 256, ytrain.shape[-1]).scatter_(dim=1, index=ytrain.reshape(1,1,-1), value=1.0).size(2)

642185

In [49]:
np.arange(0 + 1024, ytrain.shape[-1] - 1024 - 16000, 16000)

array([  1024,  17024,  33024,  49024,  65024,  81024,  97024, 113024,
       129024, 145024, 161024, 177024, 193024, 209024, 225024, 241024,
       257024, 273024, 289024, 305024, 321024, 337024, 353024, 369024,
       385024, 401024, 417024, 433024, 449024, 465024, 481024, 497024,
       513024, 529024, 545024, 561024, 577024, 593024, 609024, 625024])

In [22]:
model.eval()

WaveNet(
  (start_conv): Conv1d(256, 128, kernel_size=(1,), stride=(1,))
  (ydcnn): ModuleList(
    (0): Conv(
      (conv): Conv1d(128, 256, kernel_size=(2,), stride=(1,))
    )
    (1): Conv(
      (conv): Conv1d(128, 256, kernel_size=(2,), stride=(1,), dilation=(2,))
    )
    (2): Conv(
      (conv): Conv1d(128, 256, kernel_size=(2,), stride=(1,), dilation=(4,))
    )
    (3): Conv(
      (conv): Conv1d(128, 256, kernel_size=(2,), stride=(1,), dilation=(8,))
    )
    (4): Conv(
      (conv): Conv1d(128, 256, kernel_size=(2,), stride=(1,), dilation=(16,))
    )
    (5): Conv(
      (conv): Conv1d(128, 256, kernel_size=(2,), stride=(1,), dilation=(32,))
    )
    (6): Conv(
      (conv): Conv1d(128, 256, kernel_size=(2,), stride=(1,), dilation=(64,))
    )
    (7): Conv(
      (conv): Conv1d(128, 256, kernel_size=(2,), stride=(1,), dilation=(128,))
    )
    (8): Conv(
      (conv): Conv1d(128, 256, kernel_size=(2,), stride=(1,), dilation=(256,))
    )
    (9): Conv(
      (conv): C

In [20]:
filepath = r"C:\Users\jiyun\Desktop\Jiyu\2020-2021\ESC499 - Thesis\WaveNet\magnatagatune\data\24_preludes_for_solo_piano"

In [27]:
filepath+os.listdir(filepath)[0]

'C:\\Users\\jiyun\\Desktop\\Jiyu\\2020-2021\\ESC499 - Thesis\\WaveNet\\magnatagatune\\data\\24_preludes_for_solo_pianojan_hanford-24_preludes_for_solo_piano-01-prelude_no__1_in_f_minor-30-59.mp3'

In [32]:
os.path.join(filepath, '*.mp3')

'C:\\Users\\jiyun\\Desktop\\Jiyu\\2020-2021\\ESC499 - Thesis\\WaveNet\\magnatagatune\\data\\24_preludes_for_solo_piano\\*.mp3'

In [34]:
glob.glob(os.path.join(filepath, '*.mp3'))

['C:\\Users\\jiyun\\Desktop\\Jiyu\\2020-2021\\ESC499 - Thesis\\WaveNet\\magnatagatune\\data\\24_preludes_for_solo_piano\\jan_hanford-24_preludes_for_solo_piano-01-prelude_no__1_in_f_minor-30-59.mp3',
 'C:\\Users\\jiyun\\Desktop\\Jiyu\\2020-2021\\ESC499 - Thesis\\WaveNet\\magnatagatune\\data\\24_preludes_for_solo_piano\\jan_hanford-24_preludes_for_solo_piano-02-prelude_no__2_in_g_minor-30-59.mp3',
 'C:\\Users\\jiyun\\Desktop\\Jiyu\\2020-2021\\ESC499 - Thesis\\WaveNet\\magnatagatune\\data\\24_preludes_for_solo_piano\\jan_hanford-24_preludes_for_solo_piano-02-prelude_no__2_in_g_minor-59-88.mp3',
 'C:\\Users\\jiyun\\Desktop\\Jiyu\\2020-2021\\ESC499 - Thesis\\WaveNet\\magnatagatune\\data\\24_preludes_for_solo_piano\\jan_hanford-24_preludes_for_solo_piano-03-prelude_no__3_in_a_minor-0-29.mp3',
 'C:\\Users\\jiyun\\Desktop\\Jiyu\\2020-2021\\ESC499 - Thesis\\WaveNet\\magnatagatune\\data\\24_preludes_for_solo_piano\\jan_hanford-24_preludes_for_solo_piano-04-prelude_no__4_in_f_major-0-29.mp3',
 '

In [35]:
lr.load(glob.glob(os.path.join(filepath, '*.mp3'))[0])

(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 22050)

In [15]:
import glob
filepath = r"C:\Users\jiyun\Desktop\Jiyu\2020-2021\ESC499 - Thesis\WaveNet\magnatagatune\data\24_preludes_for_solo_piano\"
glob.glob(filepath)

['C:\\Users\\jiyun\\Desktop\\Jiyu\\2020-2021\\ESC499 - Thesis\\WaveNet\\magnatagatune\\data\\24_preludes_for_solo_piano\\jan_hanford-24_preludes_for_solo_piano-01-prelude_no__1_in_f_minor-30-59.mp3',
 'C:\\Users\\jiyun\\Desktop\\Jiyu\\2020-2021\\ESC499 - Thesis\\WaveNet\\magnatagatune\\data\\24_preludes_for_solo_piano\\jan_hanford-24_preludes_for_solo_piano-02-prelude_no__2_in_g_minor-30-59.mp3',
 'C:\\Users\\jiyun\\Desktop\\Jiyu\\2020-2021\\ESC499 - Thesis\\WaveNet\\magnatagatune\\data\\24_preludes_for_solo_piano\\jan_hanford-24_preludes_for_solo_piano-02-prelude_no__2_in_g_minor-59-88.mp3',
 'C:\\Users\\jiyun\\Desktop\\Jiyu\\2020-2021\\ESC499 - Thesis\\WaveNet\\magnatagatune\\data\\24_preludes_for_solo_piano\\jan_hanford-24_preludes_for_solo_piano-03-prelude_no__3_in_a_minor-0-29.mp3',
 'C:\\Users\\jiyun\\Desktop\\Jiyu\\2020-2021\\ESC499 - Thesis\\WaveNet\\magnatagatune\\data\\24_preludes_for_solo_piano\\jan_hanford-24_preludes_for_solo_piano-04-prelude_no__4_in_f_major-0-29.mp3',
 '

In [12]:

torch.zeros(1, 256, y.shape[-1]).to('cuda').scatter_(dim=1, index=y.reshape(1,1,-1), value=1.0)

[autoreload of model failed: Traceback (most recent call last):
  File "C:\Users\jiyun\anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Users\jiyun\anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 394, in superreload
    module = reload(module)
  File "C:\Users\jiyun\anaconda3\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\jiyun\anaconda3\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 604, in _exec
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\jiyun\Desktop\Jiyu\2020-2021\ESC499 - Thesis\WaveNet

TypeError: scatter_() received an invalid combination of arguments - got (dim=int, index=numpy.ndarray, value=float, ), but expected one of:
 * (int dim, Tensor index, Tensor src)
      didn't match because some of the keywords were incorrect: value
 * (int dim, Tensor index, Tensor src, *, str reduce)
 * (int dim, Tensor index, Number value)
      didn't match because some of the arguments have invalid types: (dim=int, index=numpy.ndarray, value=float, )
 * (int dim, Tensor index, Number value, *, str reduce)


In [ ]:
[[2 ** i for i in range(self.layers)]] * self.blocks

In [8]:
def mu_law_encoding(data, mu):
    mu_x = np.sign(data) * np.log(1 + mu * np.abs(data)) / np.log(mu + 1)
    return mu_x

In [12]:
mu = mu_law_encoding(xs,classes)

In [13]:
mu.shape, xs.shape

((642185,), (642185,))

In [16]:
mu.max(), mu.min()

(0.89858073, -0.8916347)

In [17]:
xs.max(), xs.min()

(0.56794024, -0.5463184)

In [23]:
np.unique(mu).shape

(633592,)

In [18]:
bins = np.linspace(-1, 1, classes)

In [19]:
bins

array([-1.        , -0.99215686, -0.98431373, -0.97647059, -0.96862745,
       -0.96078431, -0.95294118, -0.94509804, -0.9372549 , -0.92941176,
       -0.92156863, -0.91372549, -0.90588235, -0.89803922, -0.89019608,
       -0.88235294, -0.8745098 , -0.86666667, -0.85882353, -0.85098039,
       -0.84313725, -0.83529412, -0.82745098, -0.81960784, -0.81176471,
       -0.80392157, -0.79607843, -0.78823529, -0.78039216, -0.77254902,
       -0.76470588, -0.75686275, -0.74901961, -0.74117647, -0.73333333,
       -0.7254902 , -0.71764706, -0.70980392, -0.70196078, -0.69411765,
       -0.68627451, -0.67843137, -0.67058824, -0.6627451 , -0.65490196,
       -0.64705882, -0.63921569, -0.63137255, -0.62352941, -0.61568627,
       -0.60784314, -0.6       , -0.59215686, -0.58431373, -0.57647059,
       -0.56862745, -0.56078431, -0.55294118, -0.54509804, -0.5372549 ,
       -0.52941176, -0.52156863, -0.51372549, -0.50588235, -0.49803922,
       -0.49019608, -0.48235294, -0.4745098 , -0.46666667, -0.45